check_servers_1:
  cron: "*/10 * * * *"
  class: "CheckServersWorker"
  queue: default
  args:
    api_endpoint: "http://176.57.174.169/dsapi/serverlist"

check_servers_2:
  cron: "*/10 * * * *"
  class: "CheckServersWorker"
  queue: default
  args:
    api_endpoint: "http://51.89.1.248/dsapi/serverlist"